---
title: "Behance Exploratory Analysis - Topics"
author: Nam Wook Kim
email: namwkim85@gmail.com
output: 
  html_notebook
---
**Install dependent libraries**

```{r, message=FALSE, warning=FALSE}
# require packages

if (!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}
if (!require(jsonlite)) {install.packages("jsonlite"); library(jsonlite)}
if (!require(data.table)) {install.packages("data.table"); library(data.table)}

# if (!require(plyr)) {install.packages("plyr"); library(plyr)}
# if (!require(psych)) {install.packages("psych"); library(psych)}
# if (!require(graphics)) {install.packages("graphics"); library(graphics)}
# if (!require(maps)) {install.packages("maps"); library(maps)}
# if (!require(countrycode)) {install.packages("countrycode"); library(countrycode)}
# if (!require(MASS)) {install.packages("MASS"); library(MASS)}
# if (!require(pscl)) {install.packages("pscl"); library(pscl)}
# if (!require(QuantPsyc)) {install.packages("QuantPsyc"); library(QuantPsyc)}
# if (!require(reshape2)) {install.packages("reshape2"); library(reshape2)}
if (!require(hash)) {install.packages("hash"); library(hash)}
# if (!require(proxy)) {install.packages("proxy"); library(proxy)}

```

**Load data**
```{r}
users = fread('../data/users-10.csv')
projects = fread('../data/projects-10.csv')
links = fread('../data/links-10.csv')

```
** Topic Popularity **
```{r}
cfs<-fromJSON("https://api.behance.net/v2/fields?client_id=ancBdHFrtqhJM18AUzqev2wvgjM0PGnj")
# clean the fields
cfs$fields$abbr_name<-sapply( cfs$fields[2], function(x){
  tolower(gsub(" ", "_", x))
});
systemFields<-as.vector(cfs$fields$abbr_name)

calcTopicRanks<-function(fields){
  userFields<-hash()
  a<-sapply(fields, function(f){
    if (nchar(as.character(f))!=0){
      # process users' fields concatenated by '|'
      splited<-strsplit(as.character(f), "|", fixed = TRUE)
      splited<-unlist(splited)
      sapply(splited, function(s){
        field<-tolower(gsub(" ", "_", s))
        if (field%in%systemFields==TRUE){
          if (has.key(field, userFields)==FALSE){
            userFields[[field]]<-0
          }
          userFields[[field]]<-userFields[[field]]+1
        }
        else{
          cat('not exists: ', field, '\n')
        }

      })
    
    }
  })
  # sort by the number of users for topics
  userFields<-sort(values(userFields), decreasing=TRUE)
  # return user fields
  userFields
}

visualizeRanks<-function(fields, upto){
  ranks<-data.frame(fields=names(fields[1:upto]), counts=fields[1:upto])
  # reorder factors to match colors and bars
  ranks$fill<-factor(ranks$fields, levels = ranks$fields[order(ranks$counts, decreasing=TRUE)])
  ranks$x<-as.character(1:length(ranks$fields))
  ranks$x<-factor(ranks$x, levels = ranks$x[order(ranks$counts, decreasing=TRUE)])
  ggplot(ranks, aes(x=x, y=counts, fill= fill)) +
    geom_bar(stat="identity") +
    guides(fill=guide_legend(ncol=2)) +
    labs(list(x="Fields", y="Users", fill = "Fields"))
}

allTopics<-calcTopicRanks(projects$fields)
length(allTopics)
fields<- allTopics / sqrt(sum(allTopics^2))
visualizeRanks(fields,20)
rm(allTopics)

# ggsave('topics.pdf', width=12, height=3.5) # for publication


```
How topics are related?
```{r}
# initialize topic vectors
topics<-names(allTopics)[1:20]
topicVecs<-vector('list', length(topics))
vecSize<-nrow(designs)
for (topicName in topics){
  print(topicName)
  idx<-which(topics==topicName)
  topicVecs[[idx]]<-vector(length = vecSize)
}

for (i in 1:vecSize){
  # print(i)
  f<-designs[i,]$fields
  if (nchar(as.character(f))!=0){
      splited<-strsplit(as.character(f), "|", fixed = TRUE)
      splited<-unlist(splited)
      for (j in 1:length(splited)){
        field<-tolower(gsub(" ", "_", splited[j]))
        # print(field)
        locVec<-topics==field
        if (any(locVec)){
          idx<-which(locVec)
          # print(idx)
          topicVecs[[idx]][i]<-TRUE  
        }
        
      }
  }
}


simVals<-hash()
for (i in 1:length(topics)){
  for (j in i:length(topics)){
    topicName1<-topics[i]
    topicName2<-topics[j]
    idx1<-which(topics==topicName1)
    idx2<-which(topics==topicName2)
    if (topicName1!=topicName2){
      key<-paste0(topicName1,' vs ',topicName2)
      print(key)
      
      dist(topicVecs[[idx1]],topicVecs[[idx2]], method = "Jaccard", pairwise = TRUE)
      
      excluded <-Reduce('&', rbind(topicVecs[idx1], topicVecs[idx2]))
      combined <-Reduce('|', rbind(topicVecs[idx1], topicVecs[idx2]))
      simVal<-length(excluded[excluded==TRUE])/length(combined[combined==TRUE])
      print(simVal)
      simVals[[key]]<-simVal
    }
  }
}
simVals<-sort(values(simVals), decreasing=TRUE)

```

