---
title: "Behance Exploratory Analysis - Topics"
author: Nam Wook Kim
email: namwkim85@gmail.com
output: 
  html_notebook
---
**Install dependent libraries**

```{r, message=FALSE, warning=FALSE}
# require packages

if (!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}
if (!require(jsonlite)) {install.packages("jsonlite"); library(jsonlite)}
if (!require(data.table)) {install.packages("data.table"); library(data.table)}
if (!require(poweRlaw)) {install.packages("poweRlaw"); library(poweRlaw)}
if (!require(proxy)) {install.packages("proxy"); library(proxy)}
if (!require(ggdendro)) {install.packages("ggdendro"); library(ggdendro)}
if (!require(entropy)) {install.packages("entropy"); library(entropy)}
if (!require(effsize)) {install.packages("effsize"); library(effsize)}
if (!require(dplyr)) {install.packages("dplyr"); library(dplyr)}
# if (!require(psych)) {install.packages("psych"); library(psych)}
# if (!require(graphics)) {install.packages("graphics"); library(graphics)}
# if (!require(maps)) {install.packages("maps"); library(maps)}
# if (!require(countrycode)) {install.packages("countrycode"); library(countrycode)}
# if (!require(MASS)) {install.packages("MASS"); library(MASS)}
# if (!require(pscl)) {install.packages("pscl"); library(pscl)}
# if (!require(QuantPsyc)) {install.packages("QuantPsyc"); library(QuantPsyc)}
# if (!require(reshape2)) {install.packages("reshape2"); library(reshape2)}
# if (!require(hash)) {install.packages("hash"); library(hash)}
# if (!require(proxy)) {install.packages("proxy"); library(proxy)}

```
**Load data**
```{r}
users = fread('../data/users-100.csv')
projects = fread('../data/projects-100.csv')
links = fread('../data/links-100.csv')

```
** Topic Popularity **
```{r, fig.height=3.5, fig.width=12}
cfs<-fromJSON("https://api.behance.net/v2/fields?client_id=ancBdHFrtqhJM18AUzqev2wvgjM0PGnj")
# clean the fields
cfs$fields$abbr_name<-sapply( cfs$fields[2], function(x){
  tolower(gsub(" ", "_", x))
});
systemFields<-as.vector(cfs$fields$abbr_name)


calcTopicRanks<-function(fields){
  userFields<-vector('integer', length(systemFields)+2)
  names(userFields)<-c(systemFields,'others','no_category')
  
  for (f in fields){
    
    if (nchar(as.character(f))!=0){
      # process users' fields concatenated by '|'
      splited<-strsplit(as.character(f), "|", fixed = TRUE)
      splited<-unlist(splited)
      for (s in splited){
        
        field<-tolower(gsub(" ", "_", s))
        if (field%in%systemFields==TRUE){
          userFields[field]<-userFields[field]+1
        }else{
          userFields['others']<-userFields['others']+1
        }
      }
    
    }else{
      userFields['no_category']<-userFields['no_category']+1
    }
  }
  # sort by the number of users for topics
  userFields<-sort(userFields, decreasing=TRUE)
  # return user fields
  userFields
}

visualizeRanks<-function(fields, upto){
  ranks<-data.frame(fields=names(fields[1:upto]), counts=fields[1:upto])
  # reorder factors to match colors and bars
  ranks$fill<-factor(ranks$fields, levels = ranks$fields[order(ranks$counts, decreasing=TRUE)])
  ranks$x<-as.character(1:length(ranks$fields))
  ranks$x<-factor(ranks$x, levels = ranks$x[order(ranks$counts, decreasing=TRUE)])
  ggplot(ranks, aes(x=x, y=counts, fill= fill)) +
    geom_bar(stat="identity") +
    guides(fill=guide_legend(ncol=3)) +
    labs(list(x="Fields", y="Users", fill = "Fields"))
}
allTopics<-calcTopicRanks(projects$fields)
fieldRanks<- allTopics / sum(allTopics)
rm(allTopics)

fieldRanks['others']
fieldRanks['no_category']
sum(fieldRanks[1:30])
fieldRanks<-fieldRanks[which(names(fieldRanks)!='no_category')]
fieldRanks<-fieldRanks[which(names(fieldRanks)!='others')]
length(fieldRanks)
visualizeRanks(fieldRanks,30)

# ggsave('topics.pdf', width=12, height=3.5) # for publication
```
*Power Test*
```{r}

data_pl <- conpl$new(as.vector(fieldRanks))
data_pl$setXmin(estimate_xmin(data_pl))
kst<-bootstrap_p(data_pl,no_of_sims = 100)
kst$p
rm(data_pl)
rm(kst)
```
*Compare with User Specialization from Behance*
```{r, fig.height=3.5, fig.width=12}
allTopics<-calcTopicRanks(users$fields)
userFieldRanks<- allTopics / sum(allTopics)


userFieldRanks['others']
userFieldRanks['no_category']
sum(userFieldRanks[1:5])
userFieldRanks<-userFieldRanks[which(names(userFieldRanks)!='no_category')]
userFieldRanks<-userFieldRanks[which(names(userFieldRanks)!='others')]

visualizeRanks(userFieldRanks,30)

fieldRanksN<-as.numeric(factor(names(fieldRanks), levels=names(fieldRanks)))
userFieldRanksN<-as.numeric(factor(names(userFieldRanks), levels=names(fieldRanks)))

# cor(cbind(fieldRanksN, userFieldRanksN), method="kendall", use="pairwise") 
cor.test(fieldRanksN, userFieldRanksN, method='kendall')

rm(userFieldRanks)
rm(userFieldRanksN)
rm(allTopics)

```
*Compare with popular topics*
```{r}
cbind(cfs$popular, fieldRanks[1:12])
```

*Compare with user focus data*
```{r}
# allTopics<-calcTopicRanks(subset(users, gender=='male')$fields)
# femaleUserFieldRanks<- allTopics / sum(allTopics)
# 
# allTopics<-calcTopicRanks(subset(users, gender=='female')$fields)
# maleUserFieldRanks<- allTopics / sum(allTopics)
# 
# rm(allTopics)
# 
# maleUserFieldRanks<-maleUserFieldRanks[which(names(maleUserFieldRanks)!='no_category')]
# maleUserFieldRanks<-maleUserFieldRanks[which(names(maleUserFieldRanks)!='others')]
# 
# femaleUserFieldRanks<-femaleUserFieldRanks[which(names(femaleUserFieldRanks)!='no_category')]
# femaleUserFieldRanks<-femaleUserFieldRanks[which(names(femaleUserFieldRanks)!='others')]
# 
# 
# 
# maleUserFieldRanksN<-as.numeric(factor(names(maleUserFieldRanks), levels=names(maleUserFieldRanks)))
# femaleUserFieldRanksN<-as.numeric(factor(names(femaleUserFieldRanks), levels=names(maleUserFieldRanks)))
# 
# cor(cbind(maleUserFieldRanksN, femaleUserFieldRanksN), method="kendall", use="pairwise") 
# 
# visualizeRanks(femaleUserFieldRanks,30)
# visualizeRanks(maleUserFieldRanks,30)


```
*Calculate field ranks per gender (not using User Focus)*

```{r, fig.height=3.5, fig.width=12}
gc()
female_users<-subset(users, gender=='female')
female_links<-links[links$user_id%in%female_users$user_id & links$type=='create',]
female_projects<-projects[projects$design_id%in%female_links$design_id,]


male_users<-subset(users, gender=='male')

male_links<-links[links$user_id%in%male_users$user_id & links$type=='create',]
male_projects<-projects[projects$design_id%in%male_links$design_id,]

allTopics<-calcTopicRanks(male_projects$fields)
femaleFieldRanks<- allTopics / sum(allTopics)

allTopics<-calcTopicRanks(female_projects$fields)
maleFieldRanks<- allTopics / sum(allTopics)

maleFieldRanks<-maleFieldRanks[which(names(maleFieldRanks)!='no_category')]
maleFieldRanks<-maleFieldRanks[which(names(maleFieldRanks)!='others')]

femaleFieldRanks<-femaleFieldRanks[which(names(femaleFieldRanks)!='no_category')]
femaleFieldRanks<-femaleFieldRanks[which(names(femaleFieldRanks)!='others')]


maleFieldRanksN<-as.numeric(factor(names(maleFieldRanks), levels=names(fieldRanks)))
femaleFieldRanksN<-as.numeric(factor(names(femaleFieldRanks), levels=names(fieldRanks)))

# all vs female and male
cor(cbind(fieldRanksN, maleFieldRanksN, femaleFieldRanksN), method="kendall", use="pairwise") 

# female vs male
cor.test(maleFieldRanksN,
         femaleFieldRanksN, method="kendall")
# female vs all
cor.test(femaleFieldRanksN,
         fieldRanksN, method="kendall")
# male vs all
cor.test(maleFieldRanksN,
         fieldRanksN, method="kendall")

dat <- data.frame(
    group = rep(c("male", "female"), each=length(maleFieldRanks[1:30])),
    x = c(maleFieldRanksN[1:30], femaleFieldRanksN[1:30]),
    y = c(maleFieldRanks[1:30], -femaleFieldRanks[1:30])
    
)

dat$x<-factor(dat$x)
dat$xlabels<-c(names(maleFieldRanks[1:30]), names(femaleFieldRanks[1:30]))


ggplot(dat, aes(x=x, y=y, fill=group, xlabels=xlabels)) + 
  geom_bar(stat="identity", position="identity") +
  # guides(xlabels=guide_legend(ncol=3)) +
  labs(list(x="Fields", y="Proportion", fill = "Gender"))
  

cbind(names(maleFieldRanks[1:20]), round(as.numeric(maleFieldRanks[1:20]),  digits=4)*100, names(femaleFieldRanks[1:20]),  round(as.numeric(femaleFieldRanks[1:20]),  digits=4)*100)

cbind(sum(maleFieldRanks[1:5]), sum(femaleFieldRanks[1:5]))

rm(allTopics)
rm(female_links)
rm(female_users)
rm(male_users)
rm(male_links)
rm(dat)

# rm(maleFieldRanks)
# rm(femaleFieldRanks)
rm(maleFieldRanksN)
rm(femaleFieldRanksN)


```

*How topics are related?*
```{r, fig.height=5, fig.width=4}
# initialize topic vectors for users

sum(fieldRanks[1:20]) # account for more than 90% of total topics
topics<-names(fieldRanks)[1:20]
# topic_mat<-matrix(0,nrow=length(topics), ncol=nrow(projects))
# rownames(topic_mat)<-topics

temp<-lapply(projects$fields, function(f){
  v<-vector(mode='integer', length=length(topics))
  names(v)<-topics
  
  if (nchar(as.character(f))!=0){
      splited<-strsplit(as.character(f), "|", fixed = TRUE)
      splited<-unlist(splited)
      for (s in splited){
        field<-tolower(gsub(" ", "_", s))
        if (field%in%topics==TRUE){
          v[field]<-1
        }
        
      }
  }
  v
})

topic_mat<-as.matrix(sapply(temp, unlist))
jaccdist<-dist(topic_mat, method = "Jaccard")
topic_cluster<-hclust(jaccdist, method="ward.D2")

ggdendrogram(topic_cluster, rotate = TRUE, theme_dendro = FALSE) + 
  ylab('Jaccard Distance')+
  xlab('Top 20 Topics') +
  theme(axis.title=element_text(size=9,face="bold"))

rm(temp)
rm(jaccdist)
rm(topic_mat)

ggsave('topic_clusters.pdf', width=4, height=5) # for publication
```
*Entropy of users*
```{r}

# calculate entropy (diversity) of users
setkey(links, user_id)
setkey(projects, design_id)
users$diversity<-sapply(users$user_id, function(uid){
  # uid<-users$user_id[idx]
  # cat(idx, ': ', uid, '\n')
  # derive projects created by this user
  # user_links<-links[links$user_id==uid & links$type=='create',]
  # user_projects<-projects[projects$design_id%in%user_links$design_id,]
  
  user_links<-links[J(uid)]
  user_links<-user_links[type=='create']
  user_projects<-projects[J(user_links$design_id)]
  
  # calculate user vector
  ranks<-calcTopicRanks(user_projects$fields)
  ranks<-ranks[which(names(ranks)!='no_category')]
  ranks<-ranks[which(names(ranks)!='others')]
  ranks<-ranks/sum(ranks)
  
  topic_vector<-entropy(ranks)
  topic_vector
})
ptm <- proc.time()
users$num_topics<-sapply(users$user_id, function(uid){
  # derive projects created by this user
  # user_links<-links[links$user_id==uid & links$type=='create',]
  # user_projects<-projects[projects$design_id%in%user_links$design_id,]
  user_links<-links[J(uid)]
  user_links<-user_links[type=='create']
  user_projects<-projects[J(user_links$design_id)]
  # calculate user vector
  ranks<-calcTopicRanks(user_projects$fields)
  ranks<-ranks[which(names(ranks)!='no_category')]
  ranks<-ranks[which(names(ranks)!='others')]
  ranks<-ranks/sum(ranks)

  sum(ranks>0)
})
proc.time() - ptm
# filter users with NA & sort by number of projects
filtered<-users %>% 
  filter(!is.na(diversity)) %>% 
  arrange(project_counts)

summary(users$diversity)

filtered$group<-cut(seq_along(filtered$project_counts),3, labels=c('a', 'b', 'c'))

by(filtered$diversity, filtered$group, summary)

by(filtered$num_topics, filtered$group, summary) 

by(filtered$project_counts, filtered$group, summary) 

xrange<-rbind(as.vector(by(filtered$project_counts, filtered$group, min)),
  as.vector(by(filtered$project_counts, filtered$group, max)))
levels(filtered$group)<-c(paste0('[',xrange[1,1], ',', xrange[2,1], ']'),
                          paste0('[',xrange[1,2], ',', xrange[2,2], ']'),
                          paste0('[',xrange[1,3], ',', xrange[2,3], ']'))

ggplot(filtered, aes(factor(group), diversity)) +
  geom_boxplot(aes(fill=factor(group))) +
  ylim(0, log(68)) +
  xlab('Groups based on number of projects')+
  ylab('Diversity')

ggsave('diversity.pdf', width=4, height=3) # for publication

# t-tests by project count group
pairwise.t.test(filtered$diversity, filtered$group)
group1<-subset(filtered, group==levels(filtered$group)[1])
group2<-subset(filtered, group==levels(filtered$group)[2])
group3<-subset(filtered, group==levels(filtered$group)[3])

cohen.d(group2$diversity, group1$diversity) # effect sizes
cohen.d(group3$diversity, group2$diversity)

# specialist among generalists
specialist<-group3[group3$diversity<1.0 & group3$project_counts>1000,]

user_links<-links[links$user_id==specialist$user_id[1] & links$type=='create',]
user_projects<-projects[projects$design_id%in%user_links$design_id,]
ranks<-calcTopicRanks(user_projects$fields)
ranks<-ranks[which(names(ranks)!='no_category')]
ranks<-ranks[which(names(ranks)!='others')]
ranks<-ranks/sum(ranks)
ranks[1:10]

# generalist among generalists
generalist<-group3[group3$diversity>2.5& group3$project_counts>600]
nrow(generalist)
user_links<-links[links$user_id==generalist$user_id[1] & links$type=='create',]
user_projects<-projects[projects$design_id%in%user_links$design_id,]
ranks<-calcTopicRanks(user_projects$fields)
ranks<-ranks[which(names(ranks)!='no_category')]
ranks<-ranks[which(names(ranks)!='others')]
ranks<-ranks/sum(ranks)
ranks
generalist$project_counts
generalist$diversity
ranks[1:6]
sum(ranks[1:6])
sum(ranks>0)

# by gender by project count group
by(filtered$diversity, filtered$gender, summary)

pairwise.t.test(filtered$diversity, filtered$gender)
cohen.d(filtered$diversity, filtered$gender)

pairwise.t.test(group1$diversity, group1$gender)
pairwise.t.test(group2$diversity, group2$gender)
pairwise.t.test(group3$diversity, group2$gender)

cohen.d(group1$diversity, group1$gender)
cohen.d(group2$diversity, group2$gender)
cohen.d(group3$diversity, group3$gender)

```

*Homophily*
```{r}
# calculate entropy (diversity) of users
users$homophily<-sapply(users$user_id, function(uid){
  # calculate topic vector of projects created by this user
  # user_links<-links[links$user_id==uid & links$type=='create',]
  # user_projects<-projects[projects$design_id%in%user_links$design_id,]
  
  user_links<-links[J(uid)]
  user_links<-user_links[type=='create']
  user_projects<-projects[J(user_links$design_id)]
  
  c_ranks<-calcTopicRanks(user_projects$fields)
  c_ranks<-c_ranks[which(names(c_ranks)!='no_category')]
  c_ranks<-c_ranks[which(names(c_ranks)!='others')]
  c_ranks<-c_ranks/sum(c_ranks)

  # calculate topic vector of projects appreciated by this user
  # user_links<-links[links$user_id==uid & links$type=='appreciate',]
  # user_projects<-projects[projects$design_id%in%user_links$design_id,]
  user_links<-links[J(uid)]
  user_links<-user_links[type=='appreciate']
  user_projects<-projects[J(user_links$design_id)]
  
  
  a_ranks<-calcTopicRanks(user_projects$fields)
  a_ranks<-a_ranks[which(names(a_ranks)!='no_category')]
  a_ranks<-a_ranks[which(names(a_ranks)!='others')]
  a_ranks<-a_ranks/sum(a_ranks)
  
  # homophily
  c_ranks<-c_ranks/sqrt(sum(c_ranks^2))
  a_ranks<-a_ranks/sqrt(sum(a_ranks^2))
  homophily<-sum(c_ranks*a_ranks)
  homophily
})

  # filter users with NA & sort by number of projects
filtered<-users %>% 
  filter(!is.nan(homophily)) %>% 
  filter(!is.na(diversity)) %>% 
  arrange(diversity)

describe(filtered$homophily)

# five groups
filtered$group<-cut(seq_along(filtered$diversity),5, labels=c('a', 'b', 'c', 'd', 'e'))

xrange<-rbind(as.vector(by(filtered$diversity, filtered$group, min)),
  as.vector(by(filtered$diversity, filtered$group, max)))

levels(filtered$group)<-c(paste0('[',round(xrange[1,1],2), ',', round(xrange[2,1],2), ']'),
                          paste0('[',round(xrange[1,2],2), ',', round(xrange[2,2],2), ']'),
                          paste0('[',round(xrange[1,3],2), ',', round(xrange[2,3],2), ']'),
                          paste0('[',round(xrange[1,4],2), ',', round(xrange[2,4],2), ']'),
                          paste0('[',round(xrange[1,5],2), ',', round(xrange[2,5],2), ']'))

ggplot(filtered, aes(factor(group), homophily)) +
  geom_boxplot(aes(fill=factor(group))) +
  xlab('Groups based on diversity')+
  ylab('Homophily')

# pairwise t-test by diversity group
pairwise.t.test(filtered$homophily, filtered$group)

# three groups
filtered$group<-cut(seq_along(filtered$diversity),3, labels=c('a', 'b', 'c'))

xrange<-rbind(as.vector(by(filtered$diversity, filtered$group, min)),
  as.vector(by(filtered$diversity, filtered$group, max)))

levels(filtered$group)<-c(paste0('[',round(xrange[1,1],2), ',', round(xrange[2,1],2), ']'),
                          paste0('[',round(xrange[1,2],2), ',', round(xrange[2,2],2), ']'),
                          paste0('[',round(xrange[1,3],2), ',', round(xrange[2,3],2), ']'))

ggplot(filtered, aes(factor(group), homophily)) +
  geom_boxplot(aes(fill=factor(group))) +
  xlab('Groups based on diversity')+
  ylab('Homophily')

ggsave('homophily.pdf', width=4, height=2.5) # for publication



# pairwise t-test by diversity group
pairwise.t.test(filtered$homophily, filtered$group)
group1<-subset(filtered, group==levels(filtered$group)[1])
group2<-subset(filtered, group==levels(filtered$group)[2])
group3<-subset(filtered, group==levels(filtered$group)[3])

cohen.d(group2$homophily, group1$homophily) # effect sizes
cohen.d(group3$homophily, group2$homophily)

# homophily by gender 
by(filtered$homophily, filtered$gender, summary)

pairwise.t.test(filtered$homophily, filtered$gender)
cohen.d(filtered$homophily, filtered$gender)

ggplot(filtered, aes(factor(gender), homophily)) +
  geom_boxplot(aes(fill=factor(gender))) +
  xlab('Groups based on gender')+
  ylab('Homophily')

# homophily by gender by diversity group
pairwise.t.test(group1$homophily, group1$gender)
pairwise.t.test(group2$homophily, group2$gender)
pairwise.t.test(group3$homophily, group3$gender)

cohen.d(group1$homophily, group1$gender)
cohen.d(group2$homophily, group2$gender)
cohen.d(group3$homophily, group3$gender)

ggplot(filtered, aes(factor(gender), homophily)) +
  geom_boxplot(aes(fill=factor(gender))) +
  facet_grid(. ~ group)+
  xlab('Groups based on diversity')+
  ylab('Homophily')


```

